# Generated by Django 4.2.16 on 2026-04-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_faculty_student_subject_attendancesession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCatalog',
            fields=[
                ('subject_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(choices=[('Odd', 'Odd'), ('Even', 'Even')], max_length=10)),
            ],
        ),
    ]
