# Generated by Django 4.2.16 on 2026-04-14 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subjectcatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('canteen_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canteen_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_phone', models.CharField(max_length=20)),
                ('location_inside_campus', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_image', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.canteen')),
            ],
            options={
                'verbose_name_plural': 'Food Categories',
                'unique_together': {('canteen', 'category_name')},
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock_quantity', models.IntegerField(default=100)),
                ('is_available', models.BooleanField(default=True)),
                ('average_rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='api.canteen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.foodcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('token_status', models.CharField(choices=[('ACTIVE', 'Active'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('qr_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.canteen')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin'), ('canteen', 'Canteen Owner')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='FoodOrderItem',
            fields=[
                ('order_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.foodorder')),
            ],
        ),
        migrations.AddField(
            model_name='foodorder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CanteenOwnerProfile',
            fields=[
                ('owner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canteen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to='api.canteen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.fooditem')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('item', 'student')},
            },
        ),
    ]
