import Constants from 'expo-constants';

let ip = '127.0.0.1'; // Fallback

// expoConfig.hostUri typically holds the dynamic IP generated by Expo Go. 
// E.g., "192.168.1.135:8081"
if (Constants.expoConfig && Constants.expoConfig.hostUri) {
  ip = Constants.expoConfig.hostUri.split(':')[0];
} else if (Constants.manifest2?.extra?.expoGo?.debuggerHost) { 
  // Fallback for older expo versions if needed
  ip = Constants.manifest2.extra.expoGo.debuggerHost.split(':')[0];
}

export const API_URL = `http://${ip}:8000/api`;
export const MODEL_URL = `http://${ip}:5000`;
console.log(`[Config] Backend: ${API_URL} | Model: ${MODEL_URL}`);
