import Constants from 'expo-constants';

let ip = '127.0.0.1'; // Fallback

// expoConfig.hostUri typically holds the dynamic IP generated by Expo Go. 
if (Constants.expoConfig && Constants.expoConfig.hostUri) {
  ip = Constants.expoConfig.hostUri.split(':')[0];
} else if (Constants.manifest2?.extra?.expoGo?.debuggerHost) { 
  ip = Constants.manifest2.extra.expoGo.debuggerHost.split(':')[0];
}

export const API_URL = `http://${ip}:8000/api`;
export const MODEL_URL = `http://${ip}:5000/api`;
console.log(`[Config] Automatically detected Backend URL: ${API_URL}`);
console.log(`[Config] Automatically detected Model URL: ${MODEL_URL}`);
